server:
  port: 8083

spring:
  application:
    name: servicio-paquete
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,circuitbreakers

resilience4j:
  circuitbreaker:
    instances:
      clienteCB:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        slidingWindowSize: 5
        minimumNumberOfCalls: 2
  retry:
    instances:
      clienteRetry:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2

tarifa:
  precio-base: 10.0
  factor-peso: 5.0