spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paquete_db
    username: postgres
    password: password123
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,circuitbreakers

tarifa:
  precio-base: 10.0
  factor-peso: 5.0

resilience4j:
  circuitbreaker:
    instances:
      clienteCB:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        slidingWindowSize: 5
        minimumNumberOfCalls: 2
  retry:
    instances:
      clienteRetry:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2