server:
  port: 8082

spring:
  application:
    name: servicio-cliente
  config:
    # Esta línea es la que obliga al microservicio a buscar sus secretos
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true