spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # Toma la variable de entorno de Docker, o usa una ruta local por defecto si corres desde tu IDE
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI:file://${user.dir}/ExamenFinalBackendRepo}
          default-label: main
server:
  port: 8888