spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # Toma la variable de entorno de Docker, o usa la ruta remota de GitHub por defecto
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI:https://github.com/DanielSpecter-dotcom/ExamenFinalBackendRepo.git}
          default-label: main
server:
  port: 8888